services:
  phpfpm:
    # https://docs.docker.com/reference/compose-file/services/#user
    # https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/#interpolation-syntax
    # (used in .github/workflows/pr.yaml to run service as root)
    user: ${COMPOSE_USER:-deploy}

  node:
    image: node:22
    volumes:
      - .:/app
    working_dir: /app
