on:
  push:
    branches:
      - develop

name: Create develop release

# @see https://github.com/ncipollo/release-action
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    strategy:
      fail-fast: true
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release body
        # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        run: |
          echo "# Version ${{ github.ref }}-${{ github.sha }}" > body.md

      # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            body.md
