### Markdown
### ========
###
### Uses [itkdev/markdownlint](https://hub.docker.com/r/itkdev/markdownlint) to
### link all Markdown files (`**/*.md`) in the project.
###
### Add [markdownlint-cli configuration
### files](https://github.com/igorshubovych/markdownlint-cli?tab=readme-ov-file#configuration),
### `.markdownlint.jsonc` and `.markdownlintignore` control what is actually
### linted and how.
###

name: Markdown

on:
  pull_request:
  push:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: |
          docker run --rm --volume "$PWD":/md itkdev/markdownlint '**/*.md'
