on:
  push:
    tags:
      - '*.*.*'

name: Create Release
jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    strategy:
      fail-fast: true
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the tag/version
        run: |
          echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Make build dir
        run: |
          mkdir -p ../build

      - name: Create artifacts
        run: |
          echo "Version: $GIT_TAG" > ../build/content.txt

      - name: Create artifacts
        run: |
          echo "# Version $GIT_TAG" > body.md

      - name: Create checksum
        run: sha256sum ../build/content.txt > ../build/checksum.txt

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "../build/*.txt"
          bodyFile: "body.md"

      # - name: Upload archive
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ../build/content.txt
      #     asset_name: content/txt
      #     asset_content_type: text/plain
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload checksum
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ../build/checksum.txt
      #     asset_name: checksum.txt
      #     asset_content_type: text/plain
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
